apiVersion: stork.libopenstorage.org/v1alpha1
kind: Migration
metadata:
  name: migrate01
spec:
  clusterPair: cluster02
  includeResources: true
  startApplications: true
  namespaces:
    - student1 # update this namespace!
  #adminClusterPair: cluster02
  purgeDeletedResources: false
